#!/bin/bash
set -euo pipefail

echo "🚀 Dotfiles installer!"
echo "-------------------------------------------------"
echo
export DOTFILES_PATH="$HOME/.dotfiles"
echo "👉  Cloning into: '$DOTFILES_PATH'"

# To test that git is installed (if not macOS will prompt an installer)
git --version

git clone --depth 1 git@github.com:marydn/dotfiles.git "$DOTFILES_PATH"

"$DOTFILES_PATH/bin/dot" self install