#!/bin/bash

set -euo pipefail

echo
echo "🚀 Dotfiles installer!"
echo "-------------------------------------------------"
echo
echo "🎯 Installing basic packages"
sudo apt install -y --quiet git
echo
echo "🖊 Installing neovim"
sudo snap install --beta nvim --classic
echo
echo "🤖 Installing noobs-term"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/aaronkjones/noobs-term/master/noobs-term.sh)"
echo
# Reset colors from previous scripts
echo -e '\e[0m'
echo
sh ./scripts/customization